### ISSUE TITLE
Add Organization (Modal from Organization Index)

### ISSUE THREAD

**Issue by Jess-White** [Jess-White/boilerplate_rebuild_react_app#129]
## ✨ What new feature do you want to see?
Reconcile Add Organization (Modal) in codebase with Add Organization (Modal) in Boilerplate Figma. 

## 🧶 Acceptance Criteria
Use this page for a guide:
https://www.figma.com/file/kEoH9HCjEQHHtyo4xdyJqj/Boilerplate?node-id=182%3A72

## 🖍️ Implementation Details
A lot of this is already implemented - the task is mostly making sure that all elements on the figma are in the component/view in the codebase, and that extraneous/defunct code (e.g. toggle functions that are no longer in use) is deleted. 

<img width="640" alt="Screen Shot 2021-05-15 at 1 24 57 PM" src="https://user-images.githubusercontent.com/58121322/118374329-16a12400-b581-11eb-8df2-027877e0e059.png">

**Comment by cainwatson** [comment]
done in https://github.com/Jess-White/boilerplate_rebuild_react_app/issues/128
