### ISSUE TITLE
Edit Organization (Modal from Organization Index)

### ISSUE THREAD

**Issue by Jess-White** [Jess-White/boilerplate_rebuild_react_app#130]
## ✨ What new feature do you want to see?
A lot of this is already implemented - the task is mostly making sure that all elements on the figma are in the component/view in the codebase, and that extraneous/defunct code (e.g. toggle functions that are no longer in use) is deleted. 

## 🧶 Acceptance Criteria
Use this page for a guide:
https://www.figma.com/file/kEoH9HCjEQHHtyo4xdyJqj/Boilerplate?node-id=182%3A43

![image](https://user-images.githubusercontent.com/58121322/118374455-c7a7be80-b581-11eb-90b6-111dec5fa4bf.png)

**Comment by cainwatson** [comment]
done in https://github.com/Jess-White/boilerplate_rebuild_react_app/issues/128
