### ISSUE TITLE
Linter Configuration - VS Code Prettier extension + ES Lint config

### ISSUE THREAD

**Issue by Jess-White** [Jess-White/boilerplate_rebuild_react_app#159]
![Screen Shot 2021-06-02 at 7 13 11 PM](https://user-images.githubusercontent.com/58121322/120567261-eb1e9600-c3d6-11eb-9a25-94a4968ec411.png)

**Comment by cainwatson** [comment]
https://github.com/Jess-White/boilerplate_rebuild_react_app/pull/158#discussion_r643584591
